runtime: nodejs18

instance_class: B1
basic_scaling:
    idle_timeout: 300s
    max_instances: 1

# service: user-service

# env_variables:
    #SERVICE: 'user-service'
    #DEBUG_MODE: true
# env_variables:
  # DOMAIN: 'user-service.tecnova-backend.appspot.com'
  # DEBUG_MODE: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

